services:
  streamlit-gis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-gis-app
    ports:
      - "8502:8501"  # Map to different port to avoid conflict with main streamlit app
    environment:
      - LANGFLOW_API_URL=${LANGFLOW_API_URL:-http://host.docker.internal:7860/api/v1/run/3f229440-4079-4ee6-bcd3-341accdd9761}
      - LANGFLOW_API_KEY=${LANGFLOW_API_KEY:-}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_PRIMARY_COLOR="#28a745"
      - STREAMLIT_THEME_BACKGROUND_COLOR="#ffffff"
      - STREAMLIT_THEME_SECONDARY_BACKGROUND_COLOR="#f0f2f6"
      - STREAMLIT_THEME_TEXT_COLOR="#262730"
    volumes:
      - ./data:/app/data:ro  # Mount data directory as read-only
      - streamlit_cache:/app/.streamlit  # Cache directory
    networks:
      - gis-network
      - lang-stack_lang-stack-network  # Connect to existing Langflow network
    restart: unless-stopped
    depends_on:
      - redis-cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis-cache:
    image: redis:7-alpine
    container_name: streamlit-gis-redis
    ports:
      - "6381:6379"  # Different port to avoid conflict
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - gis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-proxy:
    image: nginx:alpine
    container_name: streamlit-gis-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - gis-network
    depends_on:
      - streamlit-gis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  streamlit_cache:
    driver: local
  nginx_logs:
    driver: local

networks:
  gis-network:
    driver: bridge
    name: gis-network
  lang-stack_lang-stack-network:
    external: true  # Connect to existing Langflow network