# This workflow automatically comments on issues labeled with 'type:enhancement' or 'type:bug'
# and adds a thumbs-up reaction to the issue to encourage community voting.

name: Community Voting
on:
  issues:
    types:
      - labeled
jobs:
  add-enhancement-comment:
    if: github.event.label.name == 'type:enhancement'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment to issue
        run: gh issue comment ${{ github.event.issue.html_url }} --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_BODY: |
            **To help Streamlit prioritize this feature, react with a 👍 (thumbs up emoji) to the initial post.**

            Your vote helps us identify which enhancements matter most to our users.

            ![Views](https://api.views-badge.org/badge/st-issue-${{ github.event.issue.number }})
      - name: Upvote issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              content: '+1'
            });
            console.log(`Added +1 reaction to issue #${context.issue.number}`);
  add-bug-comment:
    if: github.event.label.name == 'type:bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment to issue
        run: gh issue comment ${{ github.event.issue.html_url }} --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_BODY: |
            **If this issue affects you, please react with a 👍 (thumbs up emoji) to the initial post.**

            Your feedback helps us prioritize which bugs to investigate and address first.

            ![Views](https://api.views-badge.org/badge/st-issue-${{ github.event.issue.number }})
      - name: Upvote issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              content: '+1'
            });
            console.log(`Added +1 reaction to issue #${context.issue.number}`);
