name: Playwright E2E Tests - Changed Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-playwright-changed-files
  cancel-in-progress: true

jobs:
  playwright-e2e-tests-changed-files:
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 20

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        run: |
          # Get all changed files using git diff-tree
          git_output=$(git diff-tree --no-commit-id --name-only -r HEAD^ HEAD)

          # Filter files in e2e_playwright directory that match the pattern **/*_test.py
          # and exclude files in custom_components directory and deleted files
          changed_files=()
          changed_files_count=0

          while IFS= read -r file; do
            # Check if file is in e2e_playwright directory (including subdirectories)
            if [[ $file == e2e_playwright/* ]]; then
              # Check if file matches the pattern **/*_test.py
              if [[ $file == *_test.py ]]; then
                # Check if file is not in custom_components directory
                if [[ $file != *custom_components* ]]; then
                  # Check if the file still exists (not deleted)
                  if [[ -f "$file" ]]; then
                    # Remove the e2e_playwright/ prefix from the file path
                    relative_file="${file#e2e_playwright/}"
                    changed_files+=("$relative_file")
                    changed_files_count=$((changed_files_count + 1))
                  fi
                fi
              fi
            fi
          done <<< "$git_output"

          # Join the array with spaces, properly handling filenames with spaces
          joined_files=$(printf "%s " "${changed_files[@]}")
          joined_files="${joined_files% }" # Remove trailing space

          # Set outputs similar to the original action
          echo "all_changed_files=${joined_files}" >> $GITHUB_OUTPUT
          echo "all_changed_files_count=${changed_files_count}" >> $GITHUB_OUTPUT
      - name: Check changed files
        id: check_changed_files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
        run: |
          echo "Changed files count: ${CHANGED_FILES_COUNT}"
          echo "$CHANGED_FILES"
          if [[ "${CHANGED_FILES_COUNT}" -gt 5 || "${CHANGED_FILES_COUNT}" -lt 1 ]]; then
            # We limit the workflow to a max of 5 changed files, since otherwise it would
            # take too long and would not provide any benefit compared to the main playwright
            # workflow.
            echo "This workflow only supports between 1-5 changed files. Otherwise its skipping running the tests.";
            echo "run_tests=false" >> $GITHUB_OUTPUT
          else
            echo "run_tests=true" >> $GITHUB_OUTPUT
          fi
      - name: Use output
        run: |
          echo "The output value is: ${{ steps.check_changed_files.outputs.run_tests }}"
      - name: Set Python version vars
        uses: ./.github/actions/build_info
      - name: Set up Python ${{ env.PYTHON_MAX_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_MAX_VERSION }}"
      - if: steps.check_changed_files.outputs.run_tests == 'true'
        name: Setup virtual env
        uses: ./.github/actions/make_init
      - if: steps.check_changed_files.outputs.run_tests == 'true'
        name: Install playwright
        run: python -m playwright install --with-deps
      - if: steps.check_changed_files.outputs.run_tests == 'true'
        name: Run make frontend-with-profiler
        run: make frontend-with-profiler
      - name: Get short SHA
        id: short_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "sha_short=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          else
            echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          fi
      - if: steps.check_changed_files.outputs.run_tests == 'true'
        name: Run changed playwright tests
        run: |
          cd e2e_playwright
          rm -rf ./test-results
          pytest ${{ steps.changed-files.outputs.all_changed_files }} --browser webkit --browser chromium --browser firefox --tracing retain-on-failure -n auto --reruns 0 --cov=streamlit --cov-config=.coveragerc --cov-report=html
      - name: Upload failed test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright_test_results_${{ steps.short_sha.outputs.sha_short }}
          path: e2e_playwright/test-results
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report_e2e
          path: e2e_playwright/htmlcov
          retention-days: 14
