services:
  streamlit-gis-simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: streamlit-gis-simple
    ports:
      - "8504:8501"
    environment:
      - LANGFLOW_API_URL=http://host.docker.internal:7860/api/v1/run/3f229440-4079-4ee6-bcd3-341accdd9761
      - LANGFLOW_API_KEY=
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_THEME_PRIMARY_COLOR="#28a745"
    volumes:
      - ./data:/app/data:ro
    networks:
      - gis-simple-network
      - lang-stack_lang-stack-network
    restart: unless-stopped

networks:
  gis-simple-network:
    driver: bridge
    name: gis-simple-network
  lang-stack_lang-stack-network:
    external: true
