name: Build info
description: Sets common builds variables that are needed for other build steps

outputs:
  PYTHON_VERSIONS:
    description: |
      Python versions for which tests will be run.
      The oldest version is replaced by the literal "min" and
      the newest is replaced by the literal "max".
    value: ${{ steps.build_info.outputs.PYTHON_VERSIONS }}
  PYTHON_MIN_VERSION:
    description: Oldest version of Python supported by Streamlit
    value: ${{ steps.build_info.outputs.PYTHON_MIN_VERSION }}
  PYTHON_MAX_VERSION:
    description: Latest version of Python supported by Streamlit
    value: ${{ steps.build_info.outputs.PYTHON_MAX_VERSION }}

runs:
  using: composite
  steps:
    - name: Set Python version vars
      id: build_info
      shell: bash
      run: |
        PYTHON_MIN_VERSION="3.9"
        PYTHON_MAX_VERSION="3.13"
        PYTHON_VERSIONS='["min", "3.10", "3.11", "3.12", "max"]'

        echo "Setting step outputs and environment variables..."

        echo "PYTHON_MIN_VERSION=$PYTHON_MIN_VERSION" >> $GITHUB_OUTPUT
        echo "PYTHON_MAX_VERSION=$PYTHON_MAX_VERSION" >> $GITHUB_OUTPUT
        echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_OUTPUT

        echo "PYTHON_MIN_VERSION=$PYTHON_MIN_VERSION" >> $GITHUB_ENV
        echo "PYTHON_MAX_VERSION=$PYTHON_MAX_VERSION" >> $GITHUB_ENV
        echo "PYTHON_VERSIONS=$PYTHON_VERSIONS" >> $GITHUB_ENV

        echo "Done."
